//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webservice
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumnos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Alumnos()
        {
            this.Calificaciones = new HashSet<Calificaciones>();
            this.Usuario = new HashSet<Usuario>();
        }
    
        public int Id_Alumno { get; set; }
        public string Matricula { get; set; }
        public string Nombre_Completo { get; set; }
        public string Carrera { get; set; }
        public string PeriodoIngreso { get; set; }
        public int FK_Cuatrimestre { get; set; }
        public string Estatus { get; set; }
        public string Condicion { get; set; }
        public string Direccion { get; set; }
        public Nullable<long> Telefono { get; set; }
        public string Email { get; set; }
        public int FK_Tutor { get; set; }
    
        public virtual Cuatrimestres Cuatrimestres { get; set; }
        public virtual Tutor Tutor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Calificaciones> Calificaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}
