//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webservice
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materias
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Materias()
        {
            this.Calificaciones = new HashSet<Calificaciones>();
        }
    
        public int Id_Materias { get; set; }
        public string Clave { get; set; }
        public string Materia { get; set; }
        public string PrimerCorte { get; set; }
        public string SegundoCorte { get; set; }
        public string TercerCorte { get; set; }
        public string Horario { get; set; }
        public int FK_Docente { get; set; }
        public int FK_Grupo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Calificaciones> Calificaciones { get; set; }
        public virtual Docentes Docentes { get; set; }
        public virtual Grupos Grupos { get; set; }
    }
}
